//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.15 at 11:09:32 PM WEST 
//


package Jorge_Tomás;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="advert" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="imageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="price">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="fixedValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="deductibleVAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="plateNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="series" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fuel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="advertiser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mileage" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="horsePower" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="displacement" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="autonomy" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="consumption" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CO2Emissions" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="takeBack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="financing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="segment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="metallic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="transmission" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="numberOfGears" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="numberOfDoors" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="numberOfSeats" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="numberOfAirbags" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="vehicleClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="traction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="iuc" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="particlesFilter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="inspectionValidUntil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="numberOfRegisters" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="reviewBook" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="secondKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="alloyWheels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="alloyWheelsSize" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                           &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="upholstery" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="airConditioning" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="warranty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="mechanicalWarranty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="orUntil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="roofTop" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="electricRoofTop" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="nonSmoker" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cabrio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="vin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="extras">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="extra" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "advert"
})
@XmlRootElement(name = "advertisements")
public class Advertisements {

    protected List<Advertisements.Advert> advert;

    /**
     * Gets the value of the advert property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the advert property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdvert().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Advertisements.Advert }
     * 
     * 
     */
    public List<Advertisements.Advert> getAdvert() {
        if (advert == null) {
            advert = new ArrayList<Advertisements.Advert>();
        }
        return this.advert;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="imageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="price">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="fixedValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="deductibleVAT" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="plateNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="series" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="condition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="fuel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="advertiser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mileage" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="horsePower" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="displacement" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="autonomy" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="consumption" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CO2Emissions" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="takeBack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="financing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="segment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="metallic" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="transmission" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="numberOfGears" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="numberOfDoors" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="numberOfSeats" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="numberOfAirbags" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="vehicleClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="traction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="iuc" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="particlesFilter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="inspectionValidUntil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="numberOfRegisters" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="reviewBook" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="secondKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="alloyWheels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="alloyWheelsSize" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *                 &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="upholstery" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="airConditioning" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="warranty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="mechanicalWarranty" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="orUntil" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="roofTop" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="electricRoofTop" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="nonSmoker" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cabrio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="vin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="extras">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="extra" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}long" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imageUrl",
        "price",
        "fixedValue",
        "deductibleVAT",
        "plateNumber",
        "url",
        "brand",
        "model",
        "series",
        "version",
        "month",
        "year",
        "condition",
        "fuel",
        "advertiser",
        "mileage",
        "horsePower",
        "displacement",
        "autonomy",
        "consumption",
        "co2Emissions",
        "takeBack",
        "financing",
        "segment",
        "color",
        "metallic",
        "transmission",
        "numberOfGears",
        "numberOfDoors",
        "numberOfSeats",
        "numberOfAirbags",
        "vehicleClass",
        "traction",
        "iuc",
        "particlesFilter",
        "inspectionValidUntil",
        "numberOfRegisters",
        "origin",
        "reviewBook",
        "secondKey",
        "alloyWheels",
        "alloyWheelsSize",
        "upholstery",
        "airConditioning",
        "warranty",
        "mechanicalWarranty",
        "orUntil",
        "roofTop",
        "electricRoofTop",
        "nonSmoker",
        "cabrio",
        "vin",
        "extras"
    })
    public static class Advert {

        @XmlElement(required = true)
        protected String imageUrl;
        @XmlElement(required = true)
        protected Advertisements.Advert.Price price;
        protected String fixedValue;
        protected String deductibleVAT;
        protected String plateNumber;
        @XmlElement(required = true)
        protected String url;
        @XmlElement(required = true)
        protected String brand;
        @XmlElement(required = true)
        protected String model;
        protected String series;
        protected String version;
        protected String month;
        protected Integer year;
        protected String condition;
        protected String fuel;
        protected String advertiser;
        protected Advertisements.Advert.Mileage mileage;
        protected Advertisements.Advert.HorsePower horsePower;
        protected Advertisements.Advert.Displacement displacement;
        protected Advertisements.Advert.Autonomy autonomy;
        protected Advertisements.Advert.Consumption consumption;
        @XmlElement(name = "CO2Emissions")
        protected Advertisements.Advert.CO2Emissions co2Emissions;
        protected String takeBack;
        protected String financing;
        protected String segment;
        protected String color;
        protected String metallic;
        protected String transmission;
        protected Integer numberOfGears;
        protected Integer numberOfDoors;
        protected String numberOfSeats;
        protected Integer numberOfAirbags;
        protected String vehicleClass;
        protected String traction;
        protected Advertisements.Advert.Iuc iuc;
        protected String particlesFilter;
        protected String inspectionValidUntil;
        protected Integer numberOfRegisters;
        protected String origin;
        protected String reviewBook;
        protected String secondKey;
        protected String alloyWheels;
        protected Advertisements.Advert.AlloyWheelsSize alloyWheelsSize;
        protected String upholstery;
        protected String airConditioning;
        protected String warranty;
        protected String mechanicalWarranty;
        protected String orUntil;
        protected String roofTop;
        protected String electricRoofTop;
        protected String nonSmoker;
        protected String cabrio;
        protected String vin;
        @XmlElement(required = true)
        protected Advertisements.Advert.Extras extras;
        @XmlAttribute(name = "id")
        protected Long id;

        @Override
        public String toString() {
            int mileageValue;
            String mileageUnit;
            if (this.getMileage() == null){
                mileageValue = 0;
                mileageUnit = "n/a";
            } else {
                mileageValue = this.getMileage().getValue();
                mileageUnit = this.getMileage().getUnits();
            }

            return "Brand: " + this.getBrand() + " Model: " + this.getModel() + " Price: " + this.getPrice().getValue()
                    + "" +this.getPrice().getUnits() + " Mileage: "+ mileageValue + ""+mileageUnit + " Horse Power: " +this.getHorsePower().getValue()
                    + this.getHorsePower().getUnits() + " Color: " + this.getColor() + " Url: "+this.getUrl();
        }


        /**
         * Gets the value of the imageUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImageUrl() {
            return imageUrl;
        }

        /**
         * Sets the value of the imageUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImageUrl(String value) {
            this.imageUrl = value;
        }

        /**
         * Gets the value of the price property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.Price }
         *     
         */
        public Advertisements.Advert.Price getPrice() {
            return price;
        }

        /**
         * Sets the value of the price property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.Price }
         *     
         */
        public void setPrice(Advertisements.Advert.Price value) {
            this.price = value;
        }

        /**
         * Gets the value of the fixedValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFixedValue() {
            return fixedValue;
        }

        /**
         * Sets the value of the fixedValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFixedValue(String value) {
            this.fixedValue = value;
        }

        /**
         * Gets the value of the deductibleVAT property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeductibleVAT() {
            return deductibleVAT;
        }

        /**
         * Sets the value of the deductibleVAT property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeductibleVAT(String value) {
            this.deductibleVAT = value;
        }

        /**
         * Gets the value of the plateNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPlateNumber() {
            return plateNumber;
        }

        /**
         * Sets the value of the plateNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPlateNumber(String value) {
            this.plateNumber = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrl() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrl(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the brand property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBrand() {
            return brand;
        }

        /**
         * Sets the value of the brand property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBrand(String value) {
            this.brand = value;
        }

        /**
         * Gets the value of the model property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModel() {
            return model;
        }

        /**
         * Sets the value of the model property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModel(String value) {
            this.model = value;
        }

        /**
         * Gets the value of the series property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeries() {
            return series;
        }

        /**
         * Sets the value of the series property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeries(String value) {
            this.series = value;
        }

        /**
         * Gets the value of the version property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVersion() {
            return version;
        }

        /**
         * Sets the value of the version property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVersion(String value) {
            this.version = value;
        }

        /**
         * Gets the value of the month property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonth() {
            return month;
        }

        /**
         * Sets the value of the month property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonth(String value) {
            this.month = value;
        }

        /**
         * Gets the value of the year property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getYear() {
            return year;
        }

        /**
         * Sets the value of the year property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setYear(Integer value) {
            this.year = value;
        }

        /**
         * Gets the value of the condition property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCondition() {
            return condition;
        }

        /**
         * Sets the value of the condition property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCondition(String value) {
            this.condition = value;
        }

        /**
         * Gets the value of the fuel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFuel() {
            return fuel;
        }

        /**
         * Sets the value of the fuel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFuel(String value) {
            this.fuel = value;
        }

        /**
         * Gets the value of the advertiser property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdvertiser() {
            return advertiser;
        }

        /**
         * Sets the value of the advertiser property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdvertiser(String value) {
            this.advertiser = value;
        }

        /**
         * Gets the value of the mileage property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.Mileage }
         *     
         */
        public Advertisements.Advert.Mileage getMileage() {
            return mileage;
        }

        /**
         * Sets the value of the mileage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.Mileage }
         *     
         */
        public void setMileage(Advertisements.Advert.Mileage value) {
            this.mileage = value;
        }

        /**
         * Gets the value of the horsePower property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.HorsePower }
         *     
         */
        public Advertisements.Advert.HorsePower getHorsePower() {
            return horsePower;
        }

        /**
         * Sets the value of the horsePower property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.HorsePower }
         *     
         */
        public void setHorsePower(Advertisements.Advert.HorsePower value) {
            this.horsePower = value;
        }

        /**
         * Gets the value of the displacement property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.Displacement }
         *     
         */
        public Advertisements.Advert.Displacement getDisplacement() {
            return displacement;
        }

        /**
         * Sets the value of the displacement property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.Displacement }
         *     
         */
        public void setDisplacement(Advertisements.Advert.Displacement value) {
            this.displacement = value;
        }

        /**
         * Gets the value of the autonomy property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.Autonomy }
         *     
         */
        public Advertisements.Advert.Autonomy getAutonomy() {
            return autonomy;
        }

        /**
         * Sets the value of the autonomy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.Autonomy }
         *     
         */
        public void setAutonomy(Advertisements.Advert.Autonomy value) {
            this.autonomy = value;
        }

        /**
         * Gets the value of the consumption property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.Consumption }
         *     
         */
        public Advertisements.Advert.Consumption getConsumption() {
            return consumption;
        }

        /**
         * Sets the value of the consumption property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.Consumption }
         *     
         */
        public void setConsumption(Advertisements.Advert.Consumption value) {
            this.consumption = value;
        }

        /**
         * Gets the value of the co2Emissions property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.CO2Emissions }
         *     
         */
        public Advertisements.Advert.CO2Emissions getCO2Emissions() {
            return co2Emissions;
        }

        /**
         * Sets the value of the co2Emissions property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.CO2Emissions }
         *     
         */
        public void setCO2Emissions(Advertisements.Advert.CO2Emissions value) {
            this.co2Emissions = value;
        }

        /**
         * Gets the value of the takeBack property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTakeBack() {
            return takeBack;
        }

        /**
         * Sets the value of the takeBack property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTakeBack(String value) {
            this.takeBack = value;
        }

        /**
         * Gets the value of the financing property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFinancing() {
            return financing;
        }

        /**
         * Sets the value of the financing property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFinancing(String value) {
            this.financing = value;
        }

        /**
         * Gets the value of the segment property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSegment() {
            return segment;
        }

        /**
         * Sets the value of the segment property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSegment(String value) {
            this.segment = value;
        }

        /**
         * Gets the value of the color property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getColor() {
            return color;
        }

        /**
         * Sets the value of the color property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setColor(String value) {
            this.color = value;
        }

        /**
         * Gets the value of the metallic property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMetallic() {
            return metallic;
        }

        /**
         * Sets the value of the metallic property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMetallic(String value) {
            this.metallic = value;
        }

        /**
         * Gets the value of the transmission property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransmission() {
            return transmission;
        }

        /**
         * Sets the value of the transmission property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransmission(String value) {
            this.transmission = value;
        }

        /**
         * Gets the value of the numberOfGears property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumberOfGears() {
            return numberOfGears;
        }

        /**
         * Sets the value of the numberOfGears property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumberOfGears(Integer value) {
            this.numberOfGears = value;
        }

        /**
         * Gets the value of the numberOfDoors property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumberOfDoors() {
            return numberOfDoors;
        }

        /**
         * Sets the value of the numberOfDoors property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumberOfDoors(Integer value) {
            this.numberOfDoors = value;
        }

        /**
         * Gets the value of the numberOfSeats property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNumberOfSeats() {
            return numberOfSeats;
        }

        /**
         * Sets the value of the numberOfSeats property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNumberOfSeats(String value) {
            this.numberOfSeats = value;
        }

        /**
         * Gets the value of the numberOfAirbags property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumberOfAirbags() {
            return numberOfAirbags;
        }

        /**
         * Sets the value of the numberOfAirbags property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumberOfAirbags(Integer value) {
            this.numberOfAirbags = value;
        }

        /**
         * Gets the value of the vehicleClass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVehicleClass() {
            return vehicleClass;
        }

        /**
         * Sets the value of the vehicleClass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVehicleClass(String value) {
            this.vehicleClass = value;
        }

        /**
         * Gets the value of the traction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTraction() {
            return traction;
        }

        /**
         * Sets the value of the traction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTraction(String value) {
            this.traction = value;
        }

        /**
         * Gets the value of the iuc property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.Iuc }
         *     
         */
        public Advertisements.Advert.Iuc getIuc() {
            return iuc;
        }

        /**
         * Sets the value of the iuc property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.Iuc }
         *     
         */
        public void setIuc(Advertisements.Advert.Iuc value) {
            this.iuc = value;
        }

        /**
         * Gets the value of the particlesFilter property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getParticlesFilter() {
            return particlesFilter;
        }

        /**
         * Sets the value of the particlesFilter property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setParticlesFilter(String value) {
            this.particlesFilter = value;
        }

        /**
         * Gets the value of the inspectionValidUntil property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInspectionValidUntil() {
            return inspectionValidUntil;
        }

        /**
         * Sets the value of the inspectionValidUntil property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInspectionValidUntil(String value) {
            this.inspectionValidUntil = value;
        }

        /**
         * Gets the value of the numberOfRegisters property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumberOfRegisters() {
            return numberOfRegisters;
        }

        /**
         * Sets the value of the numberOfRegisters property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumberOfRegisters(Integer value) {
            this.numberOfRegisters = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the reviewBook property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReviewBook() {
            return reviewBook;
        }

        /**
         * Sets the value of the reviewBook property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReviewBook(String value) {
            this.reviewBook = value;
        }

        /**
         * Gets the value of the secondKey property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSecondKey() {
            return secondKey;
        }

        /**
         * Sets the value of the secondKey property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSecondKey(String value) {
            this.secondKey = value;
        }

        /**
         * Gets the value of the alloyWheels property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlloyWheels() {
            return alloyWheels;
        }

        /**
         * Sets the value of the alloyWheels property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlloyWheels(String value) {
            this.alloyWheels = value;
        }

        /**
         * Gets the value of the alloyWheelsSize property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.AlloyWheelsSize }
         *     
         */
        public Advertisements.Advert.AlloyWheelsSize getAlloyWheelsSize() {
            return alloyWheelsSize;
        }

        /**
         * Sets the value of the alloyWheelsSize property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.AlloyWheelsSize }
         *     
         */
        public void setAlloyWheelsSize(Advertisements.Advert.AlloyWheelsSize value) {
            this.alloyWheelsSize = value;
        }

        /**
         * Gets the value of the upholstery property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUpholstery() {
            return upholstery;
        }

        /**
         * Sets the value of the upholstery property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUpholstery(String value) {
            this.upholstery = value;
        }

        /**
         * Gets the value of the airConditioning property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAirConditioning() {
            return airConditioning;
        }

        /**
         * Sets the value of the airConditioning property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAirConditioning(String value) {
            this.airConditioning = value;
        }

        /**
         * Gets the value of the warranty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWarranty() {
            return warranty;
        }

        /**
         * Sets the value of the warranty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWarranty(String value) {
            this.warranty = value;
        }

        /**
         * Gets the value of the mechanicalWarranty property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMechanicalWarranty() {
            return mechanicalWarranty;
        }

        /**
         * Sets the value of the mechanicalWarranty property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMechanicalWarranty(String value) {
            this.mechanicalWarranty = value;
        }

        /**
         * Gets the value of the orUntil property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrUntil() {
            return orUntil;
        }

        /**
         * Sets the value of the orUntil property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrUntil(String value) {
            this.orUntil = value;
        }

        /**
         * Gets the value of the roofTop property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoofTop() {
            return roofTop;
        }

        /**
         * Sets the value of the roofTop property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoofTop(String value) {
            this.roofTop = value;
        }

        /**
         * Gets the value of the electricRoofTop property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getElectricRoofTop() {
            return electricRoofTop;
        }

        /**
         * Sets the value of the electricRoofTop property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setElectricRoofTop(String value) {
            this.electricRoofTop = value;
        }

        /**
         * Gets the value of the nonSmoker property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNonSmoker() {
            return nonSmoker;
        }

        /**
         * Sets the value of the nonSmoker property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNonSmoker(String value) {
            this.nonSmoker = value;
        }

        /**
         * Gets the value of the cabrio property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCabrio() {
            return cabrio;
        }

        /**
         * Sets the value of the cabrio property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCabrio(String value) {
            this.cabrio = value;
        }

        /**
         * Gets the value of the vin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVin() {
            return vin;
        }

        /**
         * Sets the value of the vin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVin(String value) {
            this.vin = value;
        }

        /**
         * Gets the value of the extras property.
         * 
         * @return
         *     possible object is
         *     {@link Advertisements.Advert.Extras }
         *     
         */
        public Advertisements.Advert.Extras getExtras() {
            return extras;
        }

        /**
         * Sets the value of the extras property.
         * 
         * @param value
         *     allowed object is
         *     {@link Advertisements.Advert.Extras }
         *     
         */
        public void setExtras(Advertisements.Advert.Extras value) {
            this.extras = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link Long }
         *     
         */
        public Long getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link Long }
         *     
         */
        public void setId(Long value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class AlloyWheelsSize {

            @XmlValue
            protected int value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Autonomy {

            @XmlValue
            protected int value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class CO2Emissions {

            @XmlValue
            protected int value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Consumption {

            @XmlValue
            protected float value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Displacement {

            @XmlValue
            protected int value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="extra" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "extra"
        })
        public static class Extras {

            protected List<String> extra;

            /**
             * Gets the value of the extra property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the extra property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getExtra().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getExtra() {
                if (extra == null) {
                    extra = new ArrayList<String>();
                }
                return this.extra;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class HorsePower {

            @XmlValue
            protected int value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Iuc {

            @XmlValue
            protected float value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public float getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(float value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Mileage {

            @XmlValue
            protected int value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
         *       &lt;attribute name="units" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Price {

            @XmlValue
            protected int value;
            @XmlAttribute(name = "units")
            protected String units;

            /**
             * Gets the value of the value property.
             * 
             */
            public int getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             */
            public void setValue(int value) {
                this.value = value;
            }

            /**
             * Gets the value of the units property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnits() {
                return units;
            }

            /**
             * Sets the value of the units property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnits(String value) {
                this.units = value;
            }

        }

    }

}
