//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.15 at 11:09:32 PM WEST 
//


package Jorge_Tomás;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Advertisements }
     * 
     */
    public Advertisements createAdvertisements() {
        return new Advertisements();
    }

    /**
     * Create an instance of {@link Advertisements.Advert }
     * 
     */
    public Advertisements.Advert createAdvertisementsAdvert() {
        return new Advertisements.Advert();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.Price }
     * 
     */
    public Advertisements.Advert.Price createAdvertisementsAdvertPrice() {
        return new Advertisements.Advert.Price();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.Mileage }
     * 
     */
    public Advertisements.Advert.Mileage createAdvertisementsAdvertMileage() {
        return new Advertisements.Advert.Mileage();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.HorsePower }
     * 
     */
    public Advertisements.Advert.HorsePower createAdvertisementsAdvertHorsePower() {
        return new Advertisements.Advert.HorsePower();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.Displacement }
     * 
     */
    public Advertisements.Advert.Displacement createAdvertisementsAdvertDisplacement() {
        return new Advertisements.Advert.Displacement();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.Autonomy }
     * 
     */
    public Advertisements.Advert.Autonomy createAdvertisementsAdvertAutonomy() {
        return new Advertisements.Advert.Autonomy();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.Consumption }
     * 
     */
    public Advertisements.Advert.Consumption createAdvertisementsAdvertConsumption() {
        return new Advertisements.Advert.Consumption();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.CO2Emissions }
     * 
     */
    public Advertisements.Advert.CO2Emissions createAdvertisementsAdvertCO2Emissions() {
        return new Advertisements.Advert.CO2Emissions();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.Iuc }
     * 
     */
    public Advertisements.Advert.Iuc createAdvertisementsAdvertIuc() {
        return new Advertisements.Advert.Iuc();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.AlloyWheelsSize }
     * 
     */
    public Advertisements.Advert.AlloyWheelsSize createAdvertisementsAdvertAlloyWheelsSize() {
        return new Advertisements.Advert.AlloyWheelsSize();
    }

    /**
     * Create an instance of {@link Advertisements.Advert.Extras }
     * 
     */
    public Advertisements.Advert.Extras createAdvertisementsAdvertExtras() {
        return new Advertisements.Advert.Extras();
    }

}
